# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Chris Procak/Documents/2016-2017/Computer Hardware/RegisterFile/RegisterFile.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Chris Procak/Documents/2016-2017/Computer Hardware/RegisterFile/RegisterFile.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Chris Procak/Documents/2016-2017/Computer Hardware/RegisterFile/RegisterFile.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Chris Procak/Documents/2016-2017/Computer Hardware/PROJECTS_23_LEARNING_FILES/Tutorial/tutorial.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Chris Procak/Documents/2016-2017/Computer Hardware/RegisterFile/RegisterFile.srcs/constrs_1/imports/Tutorial/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Chris Procak/Documents/2016-2017/Computer Hardware/RegisterFile/RegisterFile.srcs/constrs_1/imports/Tutorial/Basys3_Master.xdc}}]


synth_design -top RegisterFile -part xc7a35tcsg324-3


write_checkpoint -force -noxdef RegisterFile.dcp

catch { report_utilization -file RegisterFile_utilization_synth.rpt -pb RegisterFile_utilization_synth.pb }
