# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/britt.ahlgrim/Desktop/marquette/years/2016-2017/semester 2/Computer Hardware/gitRepo/Adder/Adder.cache/wt} [current_project]
set_property parent.project_path {C:/Users/britt.ahlgrim/Desktop/marquette/years/2016-2017/semester 2/Computer Hardware/gitRepo/Adder/Adder.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/britt.ahlgrim/Desktop/marquette/years/2016-2017/semester 2/Computer Hardware/gitRepo/Adder/Adder.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/britt.ahlgrim/Desktop/marquette/years/2016-2017/semester 2/Computer Hardware/gitRepo/Adder/Adder.srcs/sources_1/new/full_adder.vhd}
  {C:/Users/britt.ahlgrim/Desktop/marquette/years/2016-2017/semester 2/Computer Hardware/gitRepo/Adder/Adder.srcs/sources_1/new/thirtytwobit_adder.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/britt.ahlgrim/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/britt.ahlgrim/Downloads/Basys3_Master.xdc]


synth_design -top thirtytwobit_adder -part xc7a35tcpg236-1


write_checkpoint -force -noxdef thirtytwobit_adder.dcp

catch { report_utilization -file thirtytwobit_adder_utilization_synth.rpt -pb thirtytwobit_adder_utilization_synth.pb }
